### ISSUE TITLE
How does AG-assistant convert a task description to a prompt?

### ISSUE THREAD

**Issue by adivekar-utexas** [autogluon/autogluon-assistant#167]
I am curious about the underlying process. Which LLM papers / approaches does it use to do this?

**Comment by AnirudhDagar** [comment]
The core of AutoGluon Assistant (AG-A) is built around the concept of a Task, which encapsulates all necessary information for a tabular prediction problem. Task Inference prompts are processed by instruction-tuned LLM APIs via LangChain. The responses from these LLMs are ultimately parsed and used to populate the Task metadata. To ensure, robustness and fault tolerance, AG-A implements validation checks and appropriate fallbacks for metadata in case of an LLM based failure during the Task Inference step.
